### ISSUE TITLE
Further work

### ISSUE THREAD

**Issue by doppioandante** [xkjyeah/evince_ink#2]
Hello @xkjyeah , I've been considering implementing the ink annotations in evince and I stumbled upon your work.
I would like to ask you two things:
1) Can I base my work on yours?
2) what's the status of these patches and why didn't you end up finishing it?

I've been discussing this under the evince issue here: https://gitlab.gnome.org/GNOME/evince/-/issues/436#note_793774

**Comment by xkjyeah** [comment]
Hey Enrico,

I think I started on this project around 10 years ago, didn't I?

I didn't manage to get very far 10 years ago, and I'm going to bet it's not
going to help you much now. If you find something useful in there, feel
free to borrow the code; but I suspect you're equally good off starting
from scratch.

Good luck! =)

Daniel

**Comment by doppioandante** [comment]
Thank you Daniel, I indeed restarted from scratch but maybe something will come useful :)
